/***
*
* File: wp_vars_mysql.inc
* Auth: Damian Wojdat
* Date: 15.12.2011
* Desc: Variables related to database.
*
*************************************************************************************************************/

new db_host[12] = "192.168.1.1";
new db_user[5] = "root";
new db_database[12] = "wparty_samp";
new db_pass[9] = "comanche";

new db_result[1024];
new db_con1;
new db_con2;
new db_con3;
new db_con4;