/***
*
* File: wp_vars_gates.inc
* Auth: Damian Wojdat
* Date: 22.05.2012
* Desc: Variables related to hardcoded gates.
*
*************************************************************************************************************/

new
	gGateSfPd1a,
	gGateSfPd1b,
	gGateSfPd2a,
	gGateSfPd3a,
	gGateDmPd1a,
	gGateDmPd1aStatus,
	gGateDmPd2a,
	gGateDmPd2aStatus,
	gGatePrison1a,
	gGatePrison1b,
	gGatePrison1c, 
	gGatePrison1d,
	gGateSfParking1a,
	gGateSfParking1b,
	gGateSfMilitary1a,
	gGateSfMilitary2a,
	gGateSfMilitary3a,
	gGateSfTaxi1a,
	gGateSfTaxi2a,
	gGateSfGov1a,
	gGateSfGov2a,
	gGateSfGov3a,
	gGateSfGov4a,
	gGateSfGov5a;