/***
*
* File: wp_vars_mysql.inc
* Auth: Damian Wojdat
* Date: 15.12.2011
* Desc: Variables related to database.
*
*************************************************************************************************************/

new db_host[24] = "";
new db_user[24] = "";
new db_database[24] = "";
new db_pass[24] = "";

new db_result[1024];
new db_con1;
new db_con2;
new db_con3;
new db_con4;
new db_con5;