// stock ResetCars()
// { 
	// format(string, sizeof(string), "SELECT COUNT(ID) AS founder_count FROM `samp_users_items`");
	
	// format(string, sizeof(string), "SELECT * FROM `samp_users_items`");
	// mysql_query(string);
	// mysql_store_result();

	// mysql_fetch_row(db_result, "|");
	// split2(db_result, arrCoords, '|');
	// mysql_free_result();
	
	// tmpVar[item1] = strval(arrCoords[0]);
	// tmpVar[item2] = strval(arrCoords[1]);
	// tmpVar[item3] = strval(arrCoords[2]);
	// tmpVar[item4] = strval(arrCoords[3]);
	// tmpVar[item5] = strval(arrCoords[4]);
	// tmpVar[item1type] = strval(arrCoords[6]);
	// tmpVar[item2type] = strval(arrCoords[7]);
	// tmpVar[item3type] = strval(arrCoords[8]);
	// tmpVar[item4type] = strval(arrCoords[9]);
	// tmpVar[item5type] = strval(arrCoords[10]);
	// tmpVar[item1param] = strval(arrCoords[11]);
	// tmpVar[item2param] = strval(arrCoords[12]);
	// tmpVar[item3param] = strval(arrCoords[13]);
	// tmpVar[item4param] = strval(arrCoords[14]);
	// tmpVar[item5param] = strval(arrCoords[15]);
	// tmpVar[item1param2] = strval(arrCoords[16]);
	// tmpVar[item2param2] = strval(arrCoords[17]);
	// tmpVar[item3param2] = strval(arrCoords[18]);
	// tmpVar[item4param2] = strval(arrCoords[19]);
	// tmpVar[item5param2] = strval(arrCoords[20]);
	// tmpVar[item6] = strval(arrCoords[21]);
	// tmpVar[item7] = strval(arrCoords[22]);
	// tmpVar[item8] = strval(arrCoords[23]);
	// tmpVar[item9] = strval(arrCoords[24]);
	// tmpVar[item10] = strval(arrCoords[25]);
	// tmpVar[item6type] = strval(arrCoords[26]);
	// tmpVar[item7type] = strval(arrCoords[27]);
	// tmpVar[item8type] = strval(arrCoords[28]);
	// tmpVar[item9type] = strval(arrCoords[29]);
	// tmpVar[item10type] = strval(arrCoords[30]);
	// tmpVar[item6param] = strval(arrCoords[31]);
	// tmpVar[item7param] = strval(arrCoords[32]);
	// tmpVar[item8param] = strval(arrCoords[33]);
	// tmpVar[item9param] = strval(arrCoords[34]);
	// tmpVar[item10param] = strval(arrCoords[35]);
	// tmpVar[item6param2] = strval(arrCoords[36]);
	// tmpVar[item7param2] = strval(arrCoords[37]);
	// tmpVar[item8param2] = strval(arrCoords[38]);
	// tmpVar[item9param2] = strval(arrCoords[39]);
	// tmpVar[item10param2] = strval(arrCoords[40]);
// }
